id = "sage"
name = "Sage"
description = "Sage language support for Zed"
version = "0.5.0"
schema_version = 1
authors = ["Sage Team"]
repository = "https://github.com/sagelang/sage"

[grammars.sage]
repository = "https://github.com/sagelang/tree-sitter-sage"
commit = "915ebaa21a584e206489ca8b55d37e42ec4aab70"

[language_servers.sage-sense]
name = "sage-sense"
languages = ["Sage"]
